Add parameter ConfigFile for Invoke-NugetRestore
Saritasa/PSGallery pull request #136
Opened 2022-11-10 07:22 UTC by shalomich

2022-11-16 07:28 UTC, AntonZiminSaritasa requested changes

2022-11-16 07:28 UTC, AntonZiminSaritasa commented on modules/Saritasa.Build/Saritasa.Build.psm1
> +	  # Path to nuget config file.
Please use spaces.

2022-11-16 07:28 UTC, AntonZiminSaritasa commented on modules/Saritasa.Build/Saritasa.Build.psm1
> +        {
Follow the same style.

2022-11-16 07:28 UTC, AntonZiminSaritasa commented on modules/Saritasa.Build/Saritasa.Build.psm1
> +          $params += @('-ConfigFile', $ConfigFile)
It should be outside of the `if ($SolutionPath)` to be applied both to solutions and projects.

2022-11-17 02:17 UTC, dermeister0 commented
#137

2022-11-17 02:17 UTC, closed without merging