Create saritasa upsource powershell module
Saritasa/PSGallery pull request #48
Opened 2017-05-27 11:31 UTC by Artur2

Added functional according to task.
@dermeister0  Does I need create psd1 file for module ?

2017-05-27 14:15 UTC, Artur2 commented on modules/Saritasa.Upsource/Saritasa.Upsource.psm1
> +
Redundant space

2017-05-28 19:00 UTC, Artur2 commented
[TODO]
Consistent naming of functions

2017-05-29 06:29 UTC, dermeister0 requested changes

2017-05-29 06:29 UTC, dermeister0 commented on modules/Saritasa.Upsource/Saritasa.Upsource.psm1
> +function Get-RevisionsInReview {
Let's use the same style of plural/singular names.

Get-RevisionList
Get-RevisionWithoutReview
Get-RevisionInReview

2017-05-29 06:29 UTC, dermeister0 commented on modules/Saritasa.Upsource/Saritasa.Upsource.psm1
> +function Initialize-Upsource {
Use C#-styled brackets.

2017-05-29 06:29 UTC, dermeister0 commented on modules/Saritasa.Upsource/Saritasa.Upsource.psm1
> +
Fix static analysis issues.

    Invoke-ScriptAnalyzer modules\Saritasa.Upsource\Saritasa.Upsource.psm1

2017-05-29 06:29 UTC, dermeister0 commented on modules/Saritasa.Upsource/Saritasa.Upsource.psm1
> +function Convert-Time {
**Convert** is not valid verb.

    Get-Verb

Name if ConvertTime, since it's a local function, not a public cmdlet.

2017-05-29 06:29 UTC, dermeister0 commented on modules/Saritasa.Upsource/Saritasa.Upsource.psm1
> +    Encoding string to base64
Write correct .SYNOPSIS blocks. See Saritasa.Build.psm1 as example.

2017-05-29 06:29 UTC, dermeister0 commented on modules/Saritasa.Upsource/Saritasa.Upsource.psm1
> +        [string[]]$Stopwords
Describe how Stopwords param works.

2017-05-29 06:29 UTC, dermeister0 commented on modules/Saritasa.Upsource/Saritasa.Upsource.psm1
> +    $result.result.reviews.reviewId.reviewId | ForEach-Object { $reviewIds += $_ }
Is it the same if you return **$result.result.reviews.reviewId.reviewId**?

2017-05-29 06:29 UTC, dermeister0 commented on modules/Saritasa.Upsource/Saritasa.Upsource.psm1
> +function Get-RevisionsList {
Get-Revision

2017-05-29 06:29 UTC, dermeister0 commented on modules/Saritasa.Upsource/Saritasa.Upsource.psm1
> +function Get-RevisionListFiltered {
Get-Revision with optional params.

2017-05-29 06:29 UTC, dermeister0 commented on modules/Saritasa.Upsource/Saritasa.Upsource.psm1
> +function Get-ReviewsList {
Get-Review

2017-05-29 06:29 UTC, dermeister0 commented on modules/Saritasa.Upsource/Saritasa.Upsource.psm1
> +            $userIds += $_.Author
Trim trailing whitespace in source code.

2017-05-29 06:29 UTC, dermeister0 commented on modules/Saritasa.Upsource/Saritasa.Upsource.psm1
> +                $Stopwords | ForEach-Object {
Useless loop.

2017-05-29 06:29 UTC, dermeister0 commented on modules/Saritasa.Upsource/Saritasa.Upsource.psm1
> +    $startDateString = $from.Date.ToString("yyyy-MMM-dd")
$from == $from.Date in this case.

2017-05-29 06:29 UTC, dermeister0 commented on modules/Saritasa.Upsource/Saritasa.Upsource.psm1
> +function Get-UserInfo {
Is it public or private function?

2017-05-29 08:04 UTC, Artur2 commented on modules/Saritasa.Upsource/Saritasa.Upsource.psm1
> +function Get-UserInfo {
@dermeister0  private, I don't export this within module

2017-05-29 08:37 UTC, dermeister0 approved these changes

2017-05-29 08:37 UTC, dermeister0 commented on modules/Saritasa.Upsource/Saritasa.Upsource.psm1
> +    [CmdletBinding()]
Functions do not need CmdletBinding attribute. Keep it for cmdlets.

2017-05-29 08:37 UTC, dermeister0 commented on modules/Saritasa.Upsource/Saritasa.Upsource.psm1
> +
psd1:
Jetbrains -> JetBrains
Fill LicenseUri, ProjectUri, Tags.

2017-05-29 09:36 UTC, merged